model_list: # https://docs.litellm.ai/docs/providers/ https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json
  - model_name: gpt-5.2
    litellm_params:
      model: openai/xxxxxx
      api_base: https://xxxxxx.example.com
      api_key: sk-xxxxxx
    model_info:
      "cache_creation_input_token_cost": 0
      "cache_read_input_token_cost": 1.75e-07
      "input_cost_per_token": 1.75e-06
      "output_cost_per_token": 1.4e-05
      "max_input_tokens": 272000
      "max_output_tokens": 128000
      "max_tokens": 128000
      "mode": "chat"
      "supports_function_calling": true
      "supports_prompt_caching": true
      "supports_reasoning": true
      "supports_tool_choice": true
      "supports_native_streaming": true

  - model_name: gemini-2.5-pro
    litellm_params:
      model: openai/xxxxxx
      api_base: https://xxxxxx.example.com
      api_key: sk-xxxxxx
    model_info:
      "cache_creation_input_token_cost": 0
      "cache_read_input_token_cost": 1.25e-07
      "input_cost_per_token": 1.25e-06
      "output_cost_per_token": 1e-05
      "max_input_tokens": 1048576
      "max_output_tokens": 65535
      "max_tokens": 65535
      "mode": "chat"
      "supports_function_calling": true
      "supports_prompt_caching": true
      "supports_reasoning": true
      "supports_tool_choice": true
      "supports_native_streaming": true

  - model_name: glm-4.7
    litellm_params:
      model: openai/xxxxxx
      api_base: https://xxxxxx.example.com
      api_key: sk-xxxxxx
    model_info:
      "cache_creation_input_token_cost": 0
      "cache_read_input_token_cost": 1.1e-07
      "input_cost_per_token": 6e-07
      "output_cost_per_token": 2.2e-06
      "max_input_tokens": 200000
      "max_output_tokens": 128000
      "max_tokens": 128000
      "mode": "chat"
      "supports_function_calling": true
      "supports_prompt_caching": true
      "supports_reasoning": true
      "supports_tool_choice": true
      "supports_native_streaming": true

  - model_name: deepseek-v3.2
    litellm_params:
      model: openai/xxxxxx
      api_base: https://xxxxxx.example.com
      api_key: sk-xxxxxx
    model_info:
      "cache_creation_input_token_cost": 0
      "input_cost_per_token_cache_hit": 2.8e-08
      "input_cost_per_token": 2.8e-07
      "output_cost_per_token": 4.2e-07
      "max_input_tokens": 163840
      "max_output_tokens": 163840
      "max_tokens": 163840
      "mode": "chat"
      "supports_function_calling": true
      "supports_prompt_caching": true
      "supports_reasoning": true
      "supports_tool_choice": true
      "supports_native_streaming": true

general_settings:
  disable_master_key_return: true
  disable_spend_logs: true
  disable_error_logs: true

litellm_settings:
  num_retries: 1
  request_timeout: 240
  set_verbose: false
  callbacks: # should mount into /app
    - traj_logger.traj_logger_instance
  global_disable_no_log_param: true
  allow_dynamic_callback_disabling: false

router_settings:
  disable_cooldowns: true
  retry_policy:
    AuthenticationErrorRetries: 1
    TimeoutErrorRetries: 5
    RateLimitErrorRetries: 5
    ContentPolicyViolationErrorRetries: 0
    InternalServerErrorRetries: 5 # http status >=500, maybe bad gateway or gateway timeout
